# Generated by Django 4.2.3 on 2023-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='summary',
        ),
        migrations.AddField(
            model_name='package',
            name='person',
            field=models.IntegerField(default=1),
        ),
    ]
