# Generated by Django 4.2.3 on 2023-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_package_summary_package_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.FloatField(default=5, max_length=1),
        ),
    ]
