# Generated by Django 4.2.3 on 2023-07-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_package_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='country_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='description_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
